# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    jms_serializer.serialized_name_annotation_strategy.class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy
services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    jms_serializer.object_constructor:
        alias: jms_serializer.doctrine_object_constructor
        public: false

    appBundle.role_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments: [AppBundle\Entity\Role, ]

    security.role_hierarchy:
        class: AppBundle\Security\Role\DynamicRoleHierarchy
        arguments: ["@appBundle.role_repository"]
        public: false